apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-pods
  template:
    metadata:
      labels:
        name: mongodb-pods
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports: 
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password


---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    name: mongodb-pods 
  ports:
  - port: 27017
    targetPort: 27017
